spring:
  application:
    name: validator

  datasource:
    url: jdbc:h2:mem:testDb
    driverClassName: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
  h2:
    console:
      enabled: true
